export const mockSalons = [
  {
    id: '1',
    name: 'Glam Haven Salon',
    location: 'Avondale, Harare',
    neighborhood: 'Avondale',
    phone: '+263 77 123 4567',
    services: ['Box Braids', 'Weaves', 'Natural Styles', 'Nails'],
    priceRange: '$20-$60',
    rating: 4.8,
    reviews: 156,
    imageUrl: '/images/salons/salon1.jpg',
  },
  {
    id: '2',
    name: 'Mai Tashie Salon',
    location: 'Highlands, Harare',
    neighborhood: 'Highlands',
    phone: '+263 77 234 5678',
    services: ['Cornrows', 'Locks', 'Twists', 'Nails'],
    priceRange: '$30-$80',
    rating: 4.6,
    reviews: 94,
    imageUrl: '/images/salons/salon2.jpg',
  },
  {
    id: '3',
    name: 'Kasi Braids Hub',
    location: 'Mbare, Harare',
    neighborhood: 'Mbare',
    phone: '+263 77 345 6789',
    services: ['Box Braids', 'Weaves', 'Nails'],
    priceRange: '$15-$40',
    rating: 4.4,
    reviews: 203,
    imageUrl: '/images/salons/salon3.jpg',
  },
  {
    id: '4',
    name: 'Mai Mhofu',
    location: 'Eastlea, Harare',
    neighborhood: 'Eastlea',
    phone: '+263 77 456 7890',
    services: ['Weaves', 'Natural Styles', 'Lashes', 'Nails'],
    priceRange: '$25-$70',
    rating: 4.7,
    reviews: 127,
    imageUrl: '/images/salons/salon4.jpg',
  },
  {
    id: '5',
    name: 'A&M Braiding',
    location: 'Westgate, Harare',
    neighborhood: 'Westgate',
    phone: '+263 77 567 8901',
    services: ['Traditional Braids', 'Locks', 'Twists', 'Nails'],
    priceRange: '$20-$55',
    rating: 4.9,
    reviews: 89,
    imageUrl: '/images/salons/salon5.jpg',
  },
];

export const mockStyles = [
  {
    id: 's1',
    title: 'Golden Box Braids',
    imageUrl: '/images/styles/style1.jpg',
    stylistName: 'Lisa',
    salonId: '1',
    styleType: 'Box Braids',
    product: 'Kanekalon Gold',
    duration: '4-5 hours',
    price: '$35',
    technique: 'Traditional',
    ageGroup: '18-35',
  },
  {
    id: 's2',
    title: 'Sleek Cornrow Patterns',
    imageUrl: '/images/styles/style2.jpg',
    stylistName: 'Tinoe',
    salonId: '2',
    styleType: 'Cornrows',
    product: 'Dark & Lovely',
    duration: '2-3 hours',
    price: '$25',
    technique: 'Geometric',
    ageGroup: 'All',
  },
  {
    id: 's3',
    title: 'Locs & Culture',
    imageUrl: '/images/styles/style3.jpg',
    stylistName: 'Panashe',
    salonId: '5',
    styleType: 'Locks',
    product: 'Natural Hair Care',
    duration: 'Varies',
    price: '$45-$60',
    technique: 'Traditional',
    ageGroup: '25-60',
  },
  {
    id: 's4',
    title: 'Colorful Twists',
    imageUrl: '/images/styles/style4.jpg',
    stylistName: 'Kuda',
    salonId: '2',
    styleType: 'Twists',
    product: 'Kanekalon',
    duration: '3-4 hours',
    price: '$30',
    technique: 'Modern',
    ageGroup: 'Teens-35',
  },
  {
    id: 's5',
    title: 'Protective Weave',
    imageUrl: '/images/styles/style5.jpg',
    stylistName: 'Chido',
    salonId: '3',
    styleType: 'Weaves',
    product: 'Human Hair',
    duration: '2-3 hours',
    price: '$40',
    technique: 'Sew-In',
    ageGroup: 'All',
  },
  {
    id: 's6',
    title: 'Boho Braids with Gold',
    imageUrl: '/images/styles/style6.jpg',
    stylistName: 'Rufaro',
    salonId: '1',
    styleType: 'Box Braids',
    product: 'Kanekalon Gold',
    duration: '5-6 hours',
    price: '$50',
    technique: 'Decorative',
    ageGroup: '15-45',
  },
];

export const mockStylists = [
  {
    id: 'st1',
    name: 'Lisa Moyo',
    salonId: '1',
    specialty: 'Box Braids & Weaves',
    experience: '8 years',
    rating: 4.9,
    reviews: 156,
    bio: 'Passionate about creating beautiful, healthy braids.',
    imageUrl: '/images/stylists/stylist1.jpg',
  },
  {
    id: 'st2',
    name: 'Tinoe Ncube',
    salonId: '2',
    specialty: 'Cornrows & Modern Styles',
    experience: '5 years',
    rating: 4.8,
    reviews: 94,
    bio: 'Creative with geometric patterns and modern techniques.',
    imageUrl: '/images/stylists/stylist2.jpg',
  },
  {
    id: 'st3',
    name: 'Panashe Gudo',
    salonId: '5',
    specialty: 'Natural Hair & Locs',
    experience: '12 years',
    rating: 5.0,
    reviews: 89,
    bio: 'Specialist in natural hair care and locs maintenance.',
    imageUrl: '/images/stylists/stylist3.jpg',
  },
];

export const mockReviews = [
  {
    id: 'r1',
    salonId: '1',
    userName: 'Chipo M.',
    rating: 5,
    text: 'Amazing experience!',
    date: '2 days ago',
  },
];